services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring-net

  gateway-service:
    build:
      context: ./Gateway
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY_TIME: ${JWT_EXPIRY_TIME}
    depends_on:
      - postgres
    networks:
      - spring-net

  payment-service:
    build:
      context: ./Payment
    ports:
      - "8081:8081"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - spring-net

  notification-service:
    build:
      context: ./Notification
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - spring-net



networks:
  spring-net:
    driver: bridge
