server.port=8082

spring.application.name = notification-service

ipn.verify.url=https://ipnpb.sandbox.paypal.com/cgi-bin/webscr
spring.redis.host=localhost
spring.redis.port=6379
redis.channel.name=payments