server.port=8080
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver

spring.application.name = auth-gateway
# Gateway Routes - payment-service
spring.cloud.gateway.routes[0].id=payment-service
spring.cloud.gateway.routes[0].uri=http://payment-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Gateway Routes - webhook-service
spring.cloud.gateway.routes[1].id=webhook-service
spring.cloud.gateway.routes[1].uri=http://webhook-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/webhooks/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1